# Generated by Django 5.0.2 on 2024-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.CharField(max_length=255)),
                ('count_people', models.IntegerField()),
                ('power', models.IntegerField()),
            ],
        ),
    ]
