# Generated by Django 5.0.2 on 2024-02-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classp', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='gun',
            name='ammo_c',
        ),
        migrations.AddField(
            model_name='gun',
            name='calibre',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='gun',
            name='count_ammo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gun',
            name='serial_number',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
